version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /tmp/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
       - XPACK_SECURITY_ENABLED=false
       - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
  promec-indexer:
    image: gurvin/promec-indexer:0.1.3
    container_name: promec-indexer
    command: promec-indexer -host http://elasticsearch:9200 -directory /data/indexer -wait-mode true
    depends_on:
      - elasticsearch
    volumes:
      - /tmp/indexer:/data/indexer